// DORMS
//GET
export const GET_DORMS = 'GET_DORMS';
export const GET_DORMS_FULFILLED = 'GET_DORMS_FULFILLED';
export const GET_DORMS_REJECTED = 'GET_DORMS_REJECTED';
//ADD
export const ADD_DORM = 'ADD_DORM';
export const ADD_DORM_FULFILLED = 'ADD_DORM_FULFILLED';
export const ADD_DORM_REJECTED = 'ADD_DORM_REJECTED';
//UPDATE
export const UPDATE_DORM = 'UPDATE_DORM';
export const UPDATE_DORM_FULFILLED = 'UPDATE_DORM_FULFILLED';
export const UPDATE_DORM_REJECTED = 'UPDATE_DORM_REJECTED';
//REMOVE
// export const REMOVE_DORM = 'REMOVE_DORM';
// export const REMOVE_DORM_FULFILLED = 'REMOVE_DORM_FULFILLED';
// export const REMOVE_DORM_REJECTED = 'REMOVE_DORM_REJECTED';